### ISSUE TITLE
Csgo

### ISSUE THREAD

**Issue by DuaD491** [a1xd/rawaccel#116]
i installed rawaccel and it works perfectly with windows and every game i played yet (valorant, splitgate, fortnite etc.) but with csgo it just doesnt activate when i am actually playing (in the menu it works). i tried to install the newest version of rawaccel and it still doesnt change anything. i also tried with raw input on and off and both doesnt work. pls help me.

**Comment by a1xd** [comment]
if you can apply changes through `rawaccel.exe`, then it's working across all apps. in-game settings don't change that

one thing that might help is to make sure that you don't have any application based rules configured for your mouse

for example, another user had a similar issue, and it turned out that Logitech GHUB was changing dpi when loading a certain game, which gave the effect of accel not working as expected
