### ISSUE TITLE
This file has virus

### ISSUE THREAD

**Issue by Peeengg** [a1xd/rawaccel#192]
https://github.com/a1xd/rawaccel/tree/8350c33dfec301f55a3f1e9cc287c4bd32768dc1/writer

**Comment by torriz** [comment]
Based on what? You can see the source right there, maybe be more specific. 

You're probably experiencing a false positive.. (?)

**Comment by JacobPalecki** [comment]
This project and its releases do not contain any malicious code. Anyone who thinks otherwise is free to point out the malicious code in this open-source project. Everyone can check the signature of the driver in the releases as well.

I don't know why that website identifies a "virus", but likely it's just due to there being a driver it did not recognize.
