### ISSUE TITLE
After running "installer.exe" and restarting my pc, when I try to run "rawaccel.exe" it says that i need to run installer exe

### ISSUE THREAD

**Issue by BrunkoBest** [a1xd/rawaccel#193]
Please help.

**Comment by Gecker** [comment]
had the same issue, but it started working after i did things like:
1?) reinstalling driver a bunch of times though install\uninstall, at the end launching it "with admin rights" (the button, not the special account)
2) downloading 1.6 version and installing the driver from there, as admin
3?) restarting PC instead of turning off and on as i usually do
4?) launchingthe 1.6 version of the program first, but then i found out htat 1.6.1 began working too.

needless to say the solution was either using the 1.6 verison, or launching installer as admin, but i wanted to provide everything i did for more clarity because this issue was annoying. also, i'm on win10.

**Comment by dougg0k** [comment]
https://github.com/a1xd/rawaccel/issues/159
