### ISSUE TITLE
Rotation changes often when playing valorant

### ISSUE THREAD

**Issue by dylan-chong** [a1xd/rawaccel#196]
Play with rotation set to -3.
When I play valorant, every few minutes it seems like the rotation changes to 0 or -6 but it actually hasn't changed when i check raw accel.

The rotation can mismatch outside of valorant with valorant.
Turning off raw input buffer in val settings fixes the issue (temporarily)

I just upgraded to Windows11 so that is likely related

How can i help debug this issue?

**Comment by a1xd** [comment]
i think you are rotating your hand

**Comment by dylan-chong** [comment]
Dude… I’ve used rawAccel for a year on windows 10 without problems. I would know if I was rotating my hand.

Windows 11 was the only changed factor

**Comment by JacobPalecki** [comment]
Please review the source code. Raw Accel works as a compiled kernel driver. If any portion of RA is acting on your mouse counts (for example, sensitivity mult) then it is all working as it is all compiled from the same module. In this way RA has not changed since the release of Windows 11 which also did not change the way Windows kernel drivers work. If you think otherwise, provide a measurement.
