### ISSUE TITLE
VAC anticheat flags rawaccel

### ISSUE THREAD

**Issue by MADZOMBIKILLA** [a1xd/rawaccel#219]
i installed and restarted, loaded up rawaccel and then loaded up CS2, joined a deathmatch game and managed to play for 7 minutes then i get kick with the message [20240613174344_1](https://github.com/a1xd/rawaccel/assets/172691307/a5a813f6-df8b-49f5-bc9d-f24fe9820997), just to add context its a pretty minimal windows install, no cheats or cheat engine installed nor viruses, i played CS2 for a couple of months never had this pop up, ask me what i can do to help in terms of repeating this issue

**Comment by ktg5** [comment]
Could be something with the game; CS2 loves to corrupt itself and say something about VAC. Have you tried verifying the game files?

**Comment by MADZOMBIKILLA** [comment]
I have verified the files, the game loaded and when to ready up for a match it says "Vac is not running" and when I reopened cs2 it managed to load up a game play it fully, it didn't kick me so it might be fixed, i suppose when i was adjusting the curve a good multiple times, could be a small issue there or CS2 cooked itself overtime and did not like rawaccel running (another tad bit is that the folder for rawaccel was in a different hard drive than cs2 and steam), nevertheless i had a look online and most people didn't have this issue

**Comment by NubsOG** [comment]
i also had this issue tho im still worried of using it.
i restarted pc, verified files, restarted game and still got the same message 
i then uninstalled raw accel and then cs2 was normal
![IMG_6947](https://github.com/a1xd/rawaccel/assets/101327896/4d127604-ee42-486f-9f52-8f24d6336978)

**Comment by JacobPalecki** [comment]
At time of writing: VAC is not strict at all. It doesn't run in kernel and to my knowledge doesn't act on what is running in the kernel.
I play CS2 as my main gaming hobby. CS2 is where I test Raw Accel because it is my primary use case, and because VAC is so lenient (can run on windows in unsigned mode...). I have never received the above message.
This likely does not have to deal with installation either. Raw Accel is stateless. Every specific problem I've seen "fixed" by re-installation has been actually due to resetting the settings being passed to the driver.
There is nothing in the error message indicating that Raw Accel is involved, so we cannot conclude that this issue has to do with Raw Accel. If you think that it can only be Raw Accel due to timing of RA installation and the issue, this is likely a coincidence of timing. If enough folks play CS and have VAC issue, and enough folks install RA, then there will be some small amount of intersection even if RA has nothing to do with the VAC issue.
