### ISSUE TITLE
Call of Duty Ricochet immediate Shadow Ban

### ISSUE THREAD

**Issue by Andras-2000** [a1xd/rawaccel#238]
Dont use rawaccel in Call of Duty I got instantly flagged and shadowbanned. I just wrote a support ticket, but I really dont have high hopes on Activision.

**Comment by JacobPalecki** [comment]
Raw Accel is anti-cheat safe and so far has not resulted in any confirmed bans. Raw Accel is not a cheat.
I know of no anti-cheat software programs that tell banned users why they were banned, because that would give a signal to cheat-makers that can exploited to make better cheats. So you have no direct signal that Raw Accel is why you were banned. (Based on what I understand about shadow bans - do you even have a signal that you were banned?)
In the past, Anti-Cheat software that wanted to disallow other mouse acceleration programs have simply blocked the player from joining.
There is no further reason to discuss this until there is either a statistically significant number of players getting banned (which is not happening in our mouse accel community that has many COD players), or a user has a direct signal from the anticheat that the ban was due to Raw Accel.
