### ISSUE TITLE
Gain Cap value is treated very weirdly

### ISSUE THREAD

**Issue by GrayFace** [a1xd/rawaccel#49]
Instead of being the actual Gain limit, Cap value gets affected by Acceleration. I'd like to be able to set the actual Gain cap and Acceleration independently of one another. What makes this even worse is that UI doesn't show you the actual maximum Gain value. You need to zoom your graph to see it about right and then tweak both Cap and Acceleration until the Gain value matches the old value if you want to change just Acceleration.

**Comment by GrayFace** [comment]
That being said, best option is controlling either current Cap or the absolute Gain cap and having the value adjusted when switching between them.

**Comment by a1xd** [comment]
i think this is a decent idea, if only for UI consistency with sensitivity cap

it's a trade-off though. by setting the gain cap in terms of output, where the cap occurs (input speed) would then become dependent on acceleration

from the perspective of the driver, gain cap needs to be a value of input speed because the alternative involves much more work

so it's possible to change, but it would be up to the GUI to find an input speed that corresponds to a given output/gain value

**Comment by a1xd** [comment]
fixed in 1.5, gain cap is set in terms of gain
