### ISSUE TITLE
Converter.exe

### ISSUE THREAD

**Issue by murkamk1** [a1xd/rawaccel#70]
I want to convert these settings to rawaccel but when I try to convert it with converter.exe it makes my sensitivity 0.0001 and if I fix the sens the acceleration is too high and nothing like the acceleration in the interaccel settings
![NhKylO5](https://user-images.githubusercontent.com/78332463/106410226-6b49e480-6453-11eb-94da-41028c7e5c9c.png)

How to convert it more accurately?

**Comment by a1xd** [comment]
the issue here has to do with sensitivity cap i think, i'll fix it in the next patch

for the time being, the following should work
- run converter with your InterAccel settings
- open rawaccel, and from the menu set Advanced > Cap Style to legacy
- set sensitivity cap to some value greater than 1500, and apply

you use this config to emulate CS accel right? if that's the case, [there is a better option](https://github.com/a1xd/rawaccel/blob/master/doc/Guide.md#power)

**Comment by a1xd** [comment]
should be fixed in v1.5
