### ISSUE TITLE
MOUSE GETTING STUCK IF I HARD SWIPE

### ISSUE THREAD

**Issue by FreeHitss** [a1xd/rawaccel#79]
I'M HAVING AN ISSUE WITH THIS APP, WHENEVER I START IT MY MOUISE IS GETTING STUCK WHEN I HARD SWIPE OR FLICK IN VALORANT, I just found the settigns on youtube

Windows Sensitivity : 4
Valorant Sens : 0.195
DPI : 800
Polling Rate : 500 or 1000 (Both get stuck)

Raw Accel Settings :
Sensitivity : 0.8625
Rotation : 0
Linear

Acceleration : 0.08625
Sensitivity Cap : 2
Weight : 2
Offset : 0

IDK how to fix it, I installed MarkC mouse reg settings before using RAW accel
PLS HELP

**Comment by a1xd** [comment]
from what i've seen, this behavior usually stems from a dirty mouse sensor. try cleaning it along with your pad

interference could also be an issue if you're using a wireless mouse

and if you're only getting in-game stutter/drops, try playing with the app closed, your settings will still apply after closing

**Comment by GitLinker** [comment]
> I'M HAVING AN ISSUE WITH THIS APP, WHENEVER I START IT MY MOUISE IS GETTING STUCK WHEN I HARD SWIPE OR FLICK IN VALORANT,

Calm down on the caps man, not the end of the world. If it's actually raw accel causing issues as well, it would be more likely a driver issue than the GUI application.
>  I just found the settigns on youtube

https://www.youtube.com/watch?v=h51iDaFvp8o&ab_channel=tristan
A quick search with you putting Valorant into your issue and quickly had this popup.
From looking at your settings, they are almost a 1:1 of someone else's settings. There are nothing wrong with copy someone's settings if it feels good to you. I would look into mouse sensitivity as you may find your own settings that you like, which may or may not be used.
I have my own issues with videos like this. As they get into the subject of muscle memory and aiming, but that's a topic which you can research on your own time, and come to your own conclusion.

Because it was easy to find where you got your settings, I can guess you are using both legacy cap and gain systems. Next time, please specify that though :)

> Polling Rate: 500 or 1000 (Both get stuck)

You should try staying on polling rate 1000, just because it will have less latency. Only should really be dropping down to 500 polling if you are on wireless and saving battery power, and doing something that doesn't require low latency.
The response time from 500 and 1000 isn't much though, only being a millisecond difference. It's just more recommended if possible.

> IDK how to fix it, I installed MarkC mouse reg settings before using RAW accel
PLS HELP

MarkC mouse reg settings? http://www.esreality.com/?a=post&id=1846538?
Valorant is a recent game that released stable in 2020, it shouldn't need the mouse fix, nor should it apply it.

 @a1xd gave some pretty good responses on what could be the issue. Interference with wireless mice can be usually solved by moving the receiver closer, easily solvable with a USB extender.

It may also be the LOD (lift-off distance) of your mouse, and you will either need to look for firmware or replacing the sensor on it. If that's too advanced, I would just look into buying another mouse. (You may not like going through the trouble of taking apart your mouse, or have a spare sensor glass part on hand.)
(Delux m800, aka a Chinese wireless knockoff of the Razer Viper Mini, not even that bad to be honest, had issues with hard swipes. The company I believe has released beta software to fix this issue, and it was leaked in the deep areas of Reddit.)

If your mouse's LOD is customizable (glorious, razer, etc), look into messing with that. It's more likely your mouse than raw accel, as no one I've seen has this type of issue with it.
Worst case, you just don't use mouse acceleration. Realize many good players have appeared on the scene without the need of mouse acceleration, there even being the time where a lot of people saw it as bad. Actually, the majority of players play without mouse acceleration, as the stigma of it ruining muscle memory is deeply ingrained in the gaming community. So is muscle memory, but personal opinion.

**Comment by JacobPalecki** [comment]
This one of a similar set of issues for which there is no cause in our software, and @a1xd and @KaJe5380 gave comprehensive responses as to other possible causes. Closing.
